version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_server.sh
      timeout: 200
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 200
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 200