name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  S3_BUCKET_NAME: hjh-codebuild-bucket

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew build
      
    # src 디렉토리를 zip 파일로 압축
    - name: Zip the src directory
      run: zip -r src.zip src/
      shell: bash
    
    # AWS 권한 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-northeast-2'  # AWS 리전 설정

    # 압축한 파일을 S3로 업로드
    - name: Upload src.zip to S3
      run: aws s3 cp src.zip s3://${{ env.S3_BUCKET_NAME }}/src.zip
      shell: bash
